config/routes.rb
Rails.application.routes.draw do
  get 'gambgame/play'
  post 'gambgame/gamble'

  get 'gambtree/pending_requests'
  post 'gambtree/add_leaf_to_branch'

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end
  
  get 'home/index'
  get 'home/tutorial'
  get 'home/about'
  get 'home/new_message'
  post 'home/create_message'

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @show_tutorial = !cookies[:has_visited]
    cookies.permanent[:has_visited] = true
  end
  
  def tutorial
  end
  
  def about
    @show_tutorial = true
  end
  
  def new_message
    @message = Message.new
  end

  def create_message
    @message = Message.new(params[:message])
    
    if @message.valid?
      ContactMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_home.html.erb
<% gambgame = Gambgame.current %>
<% last_gambgame = Gambgame.order('created_at DESC').limit(2)[1] %>

<h2>Welcome to Gambtree!</h2>

<% if last_gambgame && last_gambgame.winner_gambfruit %>
  <% winner_gambfruit = last_gambgame.winner_gambfruit %>
  <% winners = last_gambgame.winners.map {|usr| usr.username} %>
  <p>Yesterday's winning Gambfruit is:</p>
  <div class="row-fluid"> 
    <div class="span3 gambfruit_options">
      <div id="gambfruit">
        <% fruit = winner_gambfruit.fruit %>
        <% color = winner_gambfruit.color %>
        <% number = winner_gambfruit.number %>
        <%= image_tag "gambfruits/#{fruit}/#{fruit}_#{color}.png", title: "Your Gambfruit", alt: "Your Gambfruit", id: "#{color}_#{fruit}", class: "gambfruit_image"%>
      </div>
      
      <div id="seal_container">
        <%= image_tag "gambfruits/numbers/shield_seal.png", id: "gambfruit_seal"%>
        <div class="crop tens">
          <img class="tens_digit num<%=number/10%>" src="/assets/numbers1.png"/>
        </div>
        <div class="crop units">
          <img class="units_digit num<%=number%10%>" src="/assets/numbers1.png"/>
        </div>
      </div>
    </div>
  </div>
  <p>Each winner was awarded with <strong><%= last_gambgame.prize %> Gambcoins</strong>. 
    The winners are: <strong><%= winners.to_sentence %></strong>.</p>
<% end %>

<p> Today's Gambgame already has <strong><%=gambgame.current_players_number%> players</strong>. The winners 
  will be awarded with <strong><%=gambgame.prize%> Gambcoins</strong>, and there can be up to 
  <strong>
    <%= gambgame.current_players_number > 0 ? Math.log2(gambgame.current_players_number + 1).truncate.to_i : 0 %> 
    winners</strong>!</p>
<p> If a new player comes in, the prize will increase in 
  <strong><%=gambgame.prize_increase%> Gambcoins</strong>. The Gambgame will end in: </p><br />
<div class="clock-container">
  <script>
  <% time_until_end = (gambgame.created_at + 1.days) - Time.now %>
  var myCountdown1 = new Countdown({time:<%=time_until_end%>,hideLine:true, rangeHi: "hour", inline: true});
  </script>
</div>
<br />
<% if user_signed_in? %>
   <% if current_user.gamble %>
     <p> Check your Gambfruits for today's Gambgame <%= link_to 'here', gambgame_play_path%>!</p>
   <% else %>
     <p> Place your gamble in today's Gambgame <%= link_to 'here', gambgame_play_path%>!</p>
   <% end %>
     <p> You can also check out <%= link_to 'your Gambtree', gambtree_pending_requests_path%>, and add more leaves to it 
       by telling your friends to join Gambtree.</p>
<% end %>

app/views/home/_prize_table_example.html.erb
<table class="tutorial-table">
<tr>
  <th>Players</th>
  <th>Maximum winners</th>
  <th>Gambcoin prize</th>
  <th>$ prize</th>
</tr>
<% (1..1101).step(100) do |players| %>
  <% players -= 1 unless players == 1%>
  <tr>
    <th><%= players %></th>
    <th><%= Math.log2(players + 1).floor %></th>
    <th><%= Gambgame.prize_for_players players %></th>
    <th>$ <%= number_with_precision (Gambgame.prize_for_players(players)/100.00), precision: 2 %></th>
  </tr>
<%end%>
</table>

app/views/home/_tutorial.html.erb
<script>
window.onload = function(){
  var offset = - 45 - ($(".navbar").css('position') == 'fixed' ? 20 : -30);
  <% 6.times do |btn_num| %>
    $("#btn-anim<%= btn_num %>").click(function() {
      $('html, body').animate({
          scrollTop: $("#step<%= btn_num + 1 %>").offset().top + offset
      }, 1500);
    });
  <% end %>
}

</script>

<div class="row-fluid">
    <div class="span4"></div> 
    <div class="span4" style="text-align: center">
      <div class="step-container">
        <div class="tutorial-step">
          <h2 class="text-center">Welcome to Gambtree!</h2>
          
          <p class="tutorial-txt">Gambtree is a gambling social network. As your network grows, you will have more chances of 
            winning, and the prizes will be bigger. This is only a prototype, so <strong>you won't have to put any money to 
              try it out</strong>.</p>
          <%= button_tag "Tell me more", id: "btn-anim0", class: "btn btn-info btn-large" %>
        </div>
      </div>
      
      <div class="step-container">
        <div id="step1" class="tutorial-step" >
          <h2 class="text-center">How does it work?</h2>
          
          <p class="tutorial-txt">Everyday, a Gambgame will be held. To participate in the Gambgame, you must spend
            a Gambseed to generate a Gambfruit. At the end of the day, a Gambfruit will be chosen
            at random. If it belongs to you or to some of the people in your network, you win! <strong>This means there will 
            always be one or more winners</strong>. </p>
          <%= button_tag "Tell me more", id: "btn-anim1", class: "btn btn-info btn-large" %>
        </div>
      </div>
      
      <div class="step-container">
        <div id="step2" class="tutorial-step" >
          <h2 class="text-center">How do I grow my network?</h2>
          
          <p class="tutorial-txt">After you join the game, you will have your own Gambtree. Your social network is
            made of all the people that belong to your Gambtree. Every Gambtree has a left branch and a right branch.
            People that join the game because of you will become leaves of one of your branches. The leaves of your 
            leaves will also be your leaves. Every leaf of your Gambtree is part of your social network. </p>
          <%= button_tag "Tell me more", id: "btn-anim2", class: "btn btn-info btn-large" %>
        </div>
      </div>
      
      <div class="step-container">
        <div id="step3" class="tutorial-step">
          <h2 class="text-center">How do I win?</h2>
          
          <p class="tutorial-txt">You do not participate in the Gambgame with all the Gambfruits in your social network.
            You participate with your own Gambfruit and all the Gambfruits in your Gambfruit branch. Your Gambfruit branch
            is the branch in your Gambtree that has the fewest players with a Gambfruit. At the end of the day, a Gambfruit 
            will be chosen at random. If you were participating with it, you win the prize! <strong>This means that there
            can be multiple winners</strong>.</p>
          <%= button_tag "Tell me more", id: "btn-anim3", class: "btn btn-info btn-large" %>
        </div>
      </div>

      <div class="step-container">
        <div id="step4" class="tutorial-step">
          <h2 class="text-center">What do I win?</h2>
          
          <p class="tutorial-txt">The prize will be given in Gambcoins. Although there isn't any real money in play 
            yet, if Gambtree shows promise, each Gambcoin will be worth $0.01 in the future. However, <strong>Gambcoins you win now cannot
            be exchanged for money</strong>. Prizes will also increase when more people join the Gambgame. Click below to check 
            the prize progression. </p>
          <%= button_tag "Tell me more", id: "btn-anim4", class: "btn btn-info btn-large" %>
        </div>
      </div>
      
      <div class="step-container">
        <div id="step5" class="tutorial-step">
          <h2 class="text-center">Prize size</h2>
          
          <p class="tutorial-txt">Prize varies depending on the # of players: </p>
          <%= render 'prize_table_example' %>
          <%= button_tag "Tell me more", id: "btn-anim5", class: "btn btn-info btn-large" %>
        </div>
      </div>
      
      <div class="step-container">
        <div id="step6" class="tutorial-step">
          <h2 class="text-center">About the money</h2>
          
          <p class="tutorial-txt">This is only a prototype, so <strong>there isn't any real money in play</strong>. However, if 
            Gambtree shows promise, the prizes will be given in real money. If you start your network now, you'll have
            a big and strong Gambtree by the time real money is in play! Initial fees to buy a Gambseed and
            participate in a Gambgame will be around $1.00 in the future. The prizes given will be of $0.01 per 
            Gambcoin. Remember, <strong>any prizes you win now cannot be exchanged for money</strong>.</p>
  
          <%= link_to "Got it! Join", new_user_registration_path(recommender: params[:recommender]), class: "btn btn-success btn-large tutorial-join-btn" %>
        </div>
      </div>
      
    </div>
    <div class="span4"/></div>
</div>

app/views/home/about.html.erb
<%= render 'tutorial' %>

app/views/home/index.html.erb
<% if @show_tutorial %>
  <%= render 'tutorial' %>
<% else %>
  <%= render 'home' %>
<% end %>

app/views/home/new_message.html.erb
<h2>Contact form</h2>

<%= form_for @message, :url => home_create_message_path do |form| %>
  <fieldset class="fields">
    <div class="field">
      <%= form.label 'Username or full name' %>
      <%= form.text_field :name, value: user_signed_in? ? current_user.username : '' %>
    </div>
    
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email, value: user_signed_in? ? current_user.email : '' %>
    </div>
    <div class="field">
      <%= form.label :subject %>
      <%= form.text_field :subject %>
    </div>
    
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body, rows: 10, class:"span8"%>
    </div>
  </fieldset>
  
  <fieldset class="actions">
    <%= form.submit "Send", class: "btn btn-primary" %>
  </fieldset>
<% end %>

app/views/home/tutorial.html.erb
<h2>Welcome to Gambtree!</h2>

<p>Thank you for joining Gambtree!</p>

<p>Below you can find a brief explanation about <strong>how to play</strong>.</p>

<h4>Your Gamble</h4>

<p>A Gambgame will be held everyday. The winners of the Gambgame will be awarded with Gambcoins (<%= image_tag "gambcoin_icon.png", size: "22x22", title: "Gambcoins", alt: "Gambcoins", class: "tutorial-info" %>). At this moment,
  Gambcoins do not have any monetary value, but if Gambtree shows promise, each Gambcoin will be worth $0.01 in the
  future. The size of the prize (<%= image_tag "prize_icon.png", size: "24x24", title: "Gambgame prize", alt: "Gambgame prize", class: "tutorial-info" %>) 
  given to each winner varies depending on the number of players participating in the Gambgame.
  Below you can see the prize progression according to the number of players (<%= image_tag "players_icon.png", size: "24x24", title: "Gambgame players", alt: "Gambgame players", class: "tutorial-info" %>): </p>
<br />

<%= render 'prize_table_example' %>
  
<p>To participate in a Gambgame, you need to make a gamble. Otherwise, you won't be able to win any prizes. To make 
  a gamble, you need to spend a Gambseed (<%= image_tag "gambseed_icon.png", size: "22x22", title: "Gambseeds", alt: "Gambseeds", class: "tutorial-info" %>) 
  to generate a Gambfruit. Gambseeds currently do not have any cost, and will
  be given to you freely every 15 days. However, in the future they will no longer be free, and will cost around 
  $1.00. To place your gamble, go to '<%= link_to 'My Gamble', gambgame_play_path %>' in the navigation bar above.</p>

<p>To generate a Gambfruit, you need to choose a type of fruit, a color, and a number for it. Your Gambfruit must be
  different from any of the other players' Gambfruits. Once you spend the Gambseed and choose a Gambfruit, you will 
  remain participating in the Gambgame. At the end of the day, a Gambfruit will be chosen at random. If it is yours, you'll be
  one of the Gambgame winners!</p>
  
<p>However, there is another way to become a winner. If the chosen Gambfruit belongs to your Gambfruit branch,
  you'll win the prize. This is explained in more detail in the following section. </p>  
<br />

<h4>Your Gambtree</h4>

<p>Every user, including you, has his or her own Gambtree. To check it out, go to '<%= link_to 'My Gambtree', gambtree_pending_requests_path %>' in the navigation 
  bar above. You'll have higher chances of winning if you have a big Gambtree. To grow your Gambtree, you'll
  have to add leaves to its branches. A Gambtree has a left and a right branch. When a player joins Gambtree and
  puts you as his or her recommender (you probably saw the field when you created your account), that player will
  become a leaf of one of your Gambtree's branches. Additionally, all the leaves of that player will also become
  leaves of your branch. </p>

<p>After a player puts you as his or her recommender, you'll receive a leaf request. To accept it, you must go to
  your Gambtree and select the branch to which you wish to attach your new leaf. Then, your player will become a leaf
  of that particular branch. Leaves can also be automatically attached to your branches when one of your leaves adds
  leaves to his or her own Gambtree, or when a new user did not give a recommender and therefore was attached randomly
  to you. </p>
  
<p>When you participate in a Gambgame, you do so with the Gambfruit that you chose and all the Gambfruits in your
  Gambfruit branch (<%= image_tag "gambfruit_icon.png", size: "24x24", title: "Your Gambfruits", alt: "Your Gambfruits", class: "tutorial-info" %>). 
  Your Gambfruit branch is the branch in your Gambtree that has the fewest amount of players with
  a Gambfruit of their own. However, you can only participate in the Gambgame if you place a gamble. Otherwise, you
  won't be able to win any prizes, regardless of whether a Gambfruit in your Gambfruit branch is chosen.</p> 
  
<p>For example, let's suppose that your Gambtree has 5 users in its left branch, 
  2 of which have a Gambfruit, and 4 users in its right branch, 3 of which have a Gambfruit. Then, your Gambfruit 
  branch would be your left branch, because it only has 2 players with a Gambfruit, which is less than the 3 
  players with a Gambfruit in the right branch. In this case, you would win if your Gambfruit or the Gambfruit of 
  any of the players in your left branch is chosen at the end of the day. </p>
  
<p>And that's it! You are ready to <%= link_to 'place your gamble', gambgame_play_path %>, 
  <%= link_to 'check out your Gambtree', gambtree_pending_requests_path %>, and <%= link_to 'tell your friends to join', gambtree_pending_requests_path %>!</p>