config/routes.rb
Rails.application.routes.draw do
  get 'gambgame/play'
  post 'gambgame/gamble'

  get 'gambtree/pending_requests'
  post 'gambtree/add_leaf_to_branch'

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end
  
  get 'home/index'
  get 'home/tutorial'
  get 'home/about'
  get 'home/new_message'
  post 'home/create_message'

  root 'home#index'

end

app/models/gambgame.rb
class Gambgame < ActiveRecord::Base
  belongs_to :winner_gambfruit, :class_name => 'Gambfruit'
  has_many :gambles
  
  def self.current 
    Gambgame.find_by ongoing: true
  end
  
  def prize
    Gambgame.prize_for_players current_players_number
  end
  
  def self.prize_for_players num_players
    return 0 unless num_players > 0
    total_income = num_players * SEED_FEE
    gambtree_share = TARGET_MARGIN * [1, num_players/PLAYER_TARGET].min
    maximum_awards = Math.log2(num_players+1)
    prize_formula = (total_income * (1 - gambtree_share) / (maximum_awards * COIN_PRICE)).round 0
    return [prize_formula, Gambgame.prize_for_players(num_players - 1) + 1].max
  end
  
  def prize_increase
    Gambgame.prize_for_players(current_players_number + 1) - prize
  end
  
  def winners
    User.joins(:gambles).where(gambles: {gambgame: self, won: true}).order("username")
  end
  
end

app/controllers/gambgame_controller.rb
class GambgameController < ApplicationController
  before_action :authenticate_user!
  @@cheking = false
  
  def play
  end
  
  def gamble
    errors = []
    if current_user.seeds > 0
      # Gambfruit parameter validations
      fruit = params[:fruit]
      color = params[:color]
      numberParam = params[:number] || ""
      number = numberParam.to_i
      unless FRUITS.include?(fruit)
        errors << "You put an invalid type of fruit for your Gambfruit."
      end
      unless COLORS.include?(color)
        errors <<  "You put an invalid color for your Gambfruit."
      end
      unless numberParam.is_i? && number >= 0 && number < 100
        errors << "You put an invalid number for your Gambfruit."
      end 
      
      unless errors.any?
        # User gambles' validation
        current_game = Gambgame.current
        unless current_user.gamble
          # Gambfruit validation
          gambfruit = Gambfruit.find_or_create_by fruit: fruit, color: color, number: number
          unless current_game.gambles.find_by gambfruit_id: gambfruit.id
            Gamble.create won: false, user: current_user, gambfruit: gambfruit, gambgame: current_game 
            
            current_user.seeds -= 1
            current_user.save
            
            current_game.current_players_number += 1
            current_game.save
          else
            errors << "The gambfruit you picked was already chosen by someone else."
          end
        else
          errors << "You already placed a gamble in today's Gambgame."
        end
      end
    else
      errors << "You do not have a Gambseed to participate."
    end
    
    if errors.any?
      flash[:error] = errors.first
      redirect_to gambgame_play_path
    else
      redirect_to root_path
    end
  end
  
  def self.check_ongoing_gambgame
    current_gambgame = Gambgame.find_by ongoing: true
    if current_gambgame.nil? || (current_gambgame.created_at + 1.days) < Time.now
      
      # Finish current gambgame
      unless current_gambgame.nil?
        determine_winners
        current_gambgame.ongoing = false
        current_gambgame.date_finished = Time.now
        current_gambgame.prize_paid = current_gambgame.prize
        current_gambgame.players_number = current_gambgame.current_players_number
        current_gambgame.save
      end
      # Start new gambgame
      Gambgame.create ongoing: true, current_players_number: 0
    end
  end
  
  protected
  
  def self.determine_winners
    current_game =  Gambgame.current 
    gambles = current_game.gambles
    if gambles.length > 0
      winner_position = RandomGenerator.get_random_int gambles.length - 1
      winner_gamble = gambles[winner_position]
      
      winner_players = [winner_gamble.user] + winner_gamble.user.winner_parents
      winner_players.each do |player|
        gamble = player.gamble 
        gamble.won = true
        gamble.save
        player.coins += current_game.prize
        player.save
      end
      current_game.awards_won = winner_players.length
      current_game.winner_gambfruit = winner_gamble.gambfruit
      current_game.save
    else
      current_game.awards_won = 0
      current_game.save
    end
  end
  
end

app/helpers/gambgame_helper.rb
module GambgameHelper
end

app/views/gambgame/_already_gambled.html.erb
<h2>Check your current gamble</h2>
<p> You are participating in today's Gambgame. At the end of the day, one of all 
  the players' Gambfruits will be chosen at random. If your Gambfruit or 
  one of the Gambfruits in your Gambfruit branch is chosen, you'll win the Gambgame's prize!</p><br />

<% gambfruits = current_user.participating_gambfruits %>
<p> You are currently participating with  
  <strong><%= gambfruits.length %> Gambfruit<%= 's' unless 1 == gambfruits.length %></strong>:  
</p><br />
<% col_num = 4 %>
<% (gambfruits.length/col_num + 1).times do |row_num|%>
  <div class="row-fluid">
    <% first_posn = row_num * col_num %>
    <% last_posn = first_posn + (gambfruits.length/col_num > row_num ? col_num : gambfruits.length % col_num) - 1 %>
    <% row_gambfruits = gambfruits[first_posn..last_posn] %> 
    <% row_gambfruits.each do |gambfruit| %>
      <div class="span3 gambfruit_options">
        <div id="gambfruit">
          <% fruit = gambfruit.fruit %>
          <% color = gambfruit.color %>
          <% number = gambfruit.number %>
          <%= image_tag "gambfruits/#{fruit}/#{fruit}_#{color}.png", title: "Your Gambfruit", alt: "Your Gambfruit", id: "#{color}_#{fruit}", class: "gambfruit_image"%>
        </div>
        
        <div id="seal_container">
          <%= image_tag "gambfruits/numbers/shield_seal.png", id: "gambfruit_seal"%>
          <div class="crop tens">
            <img class="tens_digit num<%=number/10%>" src="/assets/numbers1.png"/>
          </div>
          <div class="crop units">
            <img class="units_digit num<%=number%10%>" src="/assets/numbers1.png"/>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/gambgame/_choose_gambfruit.html.erb
<%= javascript_include_tag '/assets/gambgame', 'data-turbolinks-track' => true %>
<h2>Choose your Gambfruit!</h2>
<p> Use a Gambseed to spring a Gambfruit, and participate in today's Gambgame. At the end of the day, one of all 
  the players' Gambfruits will be chosen at random. If your Gambfruit or 
  one of the Gambfruits in your Gambfruit branch is chosen, you'll win the Gambgame's prize!</p>

<% gambfruits = current_user.gambfruit_branch_gambfruits %>  
<p> If you play in today's Gambgame, you'll have 
  <strong><%= gambfruits.length %> other Gambfruit<%= 's' unless 1 == gambfruits.length %></strong> to participate with.  
</p>
<div class="gambfruit-selector">
  <h4 class="text-center">Select a type of fruit, a number, and a color for your Gambfruit:</h4><br />
  
  <div class="row-fluid">
    <div class="span4 gambfruit_options">
      <button id="decFruit" class="option_button">&laquo;</button>
      <% FRUITS.each do |fruit| %>
        <%= image_tag "gambfruits/#{fruit}/#{fruit}_colored.png", title: fruit.capitalize, alt: fruit.capitalize, id: fruit, class: "option_image #{'hidden_option' unless fruit == FRUITS[0]}" %>
      <% end %>
      <button id="incFruit" class="option_button">&raquo;</button>
    </div>
    
    <div class="span4 gambfruit_options">
      <button id="decNumber" class="option_button">&laquo;</button>
        <div class="crop big_num">
          <img class="tens_digit num0" src="/assets/numbers1.png"/>
        </div>
        <div class="crop big_num">
          <img class="units_digit num0" src="/assets/numbers1.png"/>
        </div>
      <button id="incNumber" class="option_button">&raquo;</button>
    </div>
    
    <div class="span4 gambfruit_options">
      <button id="decColor" class="option_button">&laquo;</button>
      <% COLORS.each do |color| %>
        <%= image_tag "gambfruits/brush/#{color}.png", title: color.capitalize, alt: color.capitalize, id: color, class: "option_image #{'hidden_option' unless color == COLORS[0]}" %>
      <% end %>
      <button id="incColor" class="option_button">&raquo;</button>
    </div>
  </div>
  
  <div class="row-fluid">
    <div class="span12 gambfruit_options">
      <br />
      <div id="gambfruit">
        <% FRUITS.each do |fruit| %>
          <% COLORS.each do |color| %>
            <%= image_tag "gambfruits/#{fruit}/#{fruit}_#{color}.png", title: "Your Gambfruit", alt: "Your Gambfruit", id: "#{color}_#{fruit}", class: "gambfruit_image #{'hidden_option' unless color == COLORS[0] && fruit == FRUITS[0]}"%>
          <% end %>
        <% end %>
      </div>
      
      <div id="seal_container">
        <%= image_tag "gambfruits/numbers/shield_seal.png", id: "gambfruit_seal"%>
        <div class="crop tens">
          <img class="tens_digit num0" src="/assets/numbers1.png"/>
        </div>
        <div class="crop units">
          <img class="units_digit num0" src="/assets/numbers1.png"/>
        </div>
      </div>
    </div>
  </div>
  
  <%= form_tag(gambgame_gamble_path, method: "post") do %>
    <%= hidden_field_tag :fruit, FRUITS[0], id: "fruit_param" %>
    <%= hidden_field_tag :color, COLORS[0], id: "color_param" %>
    <%= hidden_field_tag :number, 0, id: "number_param" %>
    <div style="text-align: center"><%= submit_tag "Gamble!", class: "btn btn-primary btn-default btn-large" %></div>
  <% end %>
<div/>

app/views/gambgame/play.html.erb
<% if current_user.gamble %>
<%= render 'already_gambled' %>
<% else %>
<%= render 'choose_gambfruit' %>
<% end %>