config/routes.rb
Rails.application.routes.draw do
  get 'gambgame/play'
  post 'gambgame/gamble'

  get 'gambtree/pending_requests'
  post 'gambtree/add_leaf_to_branch'

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end
  
  get 'home/index'
  get 'home/tutorial'
  get 'home/about'
  get 'home/new_message'
  post 'home/create_message'

  root 'home#index'

end

app/controllers/gambtree_controller.rb
class GambtreeController < ApplicationController
  before_action :authenticate_user!
  
  def pending_requests
    @gambtree = current_user.gambtree
  end
  
  def add_leaf_to_branch
    request = JoinRequest.find(params[:request_id])
    if request && !request.resolved && request.user.parent.nil? && current_user = request.receiver
      leaf = request.user
      branch = params[:to_left] == "true" ? current_user.left_branch : current_user.right_branch
      if branch.nil?
        if params[:to_left] == "true"
          current_user.left_branch = leaf
        else
          current_user.right_branch = leaf
        end
        leaf.parent = current_user
        leaf.save
        current_user.save
      else
        branch.add_leaf leaf
      end
      request.resolved = true
      request.save
      flash[:sucess] = "Leaf successfully added."
    else
      flash[:error] = "Request does not exist."
    end
    redirect_to gambtree_pending_requests_path
  end
  
end

app/helpers/gambtree_helper.rb
module GambtreeHelper
end

app/views/gambtree/pending_requests.html.erb
<% requests = current_user.pending_requests%>
<% request_num = requests.count%>
<% left_branch_num = current_user.left_branch ? current_user.left_branch.gambtree.length : 0 %>
<% right_branch_num = current_user.right_branch ? current_user.right_branch.gambtree.length : 0 %>
<% gambfruits_num = current_user.gambfruit_branch_gambfruits.length + 1 %>

<h2>Welcome to your Gambtree!</h2>
<p> Your Gambtree has <strong><%= @gambtree.length - 1 %> <%= @gambtree.length - 1 == 1 ? "leaf" : "leaves"%></strong>, 
  <strong><%= left_branch_num %></strong> in its left branch and <strong><%= right_branch_num %></strong> in its
  right branch. You gamble in the Gambgame with your own Gambfruit and all the Gambfruits 
  in your Gambfruit branch. If you participate today, you would be playing with 
  <strong><%= gambfruits_num %> Gambfruit<%= "s" if gambfruits_num > 0 %></strong>.
  You currently have <strong><%= request_num %> pending <%= request_num == 1 ? "leaf" : "leaves"%></strong> to 
  add to your Gambtree.</p>
<p> To invite your friends to Gambtree, send them this link: <strong><%= root_url(recommender: current_user.username)%></strong></p>  
  
<% if request_num > 0 %>
<br />
<p class="text-center">Add <strong><%= requests.first.user.full_name%></strong> as a new leaf of your Gambtree. To which branch do you wish to add your new leaf?</p>
<div class="row-fluid">
  <div class="span6" style="text-align: center">
    <%= link_to "Left branch", gambtree_add_leaf_to_branch_path(request_id: requests.first.id, to_left: "true"), method: :post, class: "btn btn-success btn-large" %>
  </div>
  <div class="span6" style="text-align: center">
  <%= link_to "Right branch", gambtree_add_leaf_to_branch_path(request_id: requests.first.id, to_left: "false"), method: :post, class: "btn btn-primary btn-large" %>
  </div>
</div>
<br /><br />
<% end %>

<div class="gambtree-selector">
  <h4 class="text-center">Check out your Gambtree!</h4>
  <script>
    var leaves = [
        <%= @gambtree.map{|leaf| "{lvl:#{leaf[:lvl]},posn:#{leaf[:posn]},name:\"#{leaf[:name]}\",gambling:#{leaf[:gambling]},is_leaf:#{leaf[:is_leaf].to_s},used_by_player:#{leaf[:used_by_player].to_s}}"}.join(", ").html_safe %>
    ];
  </script>
  <%= javascript_include_tag '/assets/gambtree', 'data-turbolinks-track' => true %>
  <div class="row-fluid">
    <div class="span12">
      <canvas id="gambtree">
      </canvas>
    </div>
  </div><br />
  
  <div style="text-align: center"><%= submit_tag "Show names", id: "show", class: "btn btn-primary btn-large" %></div><br />
  
  <div class="row-fluid">
    <div class="span4 text-align: center">
      <div class="text-center regular-leaf">User in your Gambtree</div>
    </div>
    <div class="span4 text-align: center">
      <div class="text-center gambling-leaf">User with a Gambfruit</div>
    </div>
    <div class="span4 text-align: center">
      <div class="text-center participating-leaf">User in Gambfruit branch</div>
    </div>
  </div>
</div>