config/routes.rb
Rails.application.routes.draw do
  get 'gambgame/play'
  post 'gambgame/gamble'

  get 'gambtree/pending_requests'
  post 'gambtree/add_leaf_to_branch'

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end
  
  get 'home/index'
  get 'home/tutorial'
  get 'home/about'
  get 'home/new_message'
  post 'home/create_message'

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Gambtree" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'favicon.ico' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body >
  	<img id="leaf" style="display: none"src="/assets/leaf.png"></img>
  	<img id="leaf-used" style="display: none"src="/assets/leaf-used.png"></img>
  	<img id="leaf-gambling" style="display: none"src="/assets/leaf-gamble.png"></img>
  	
  	<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="<%= root_path %>">Gambtree</a>
          <div class="nav-collapse collapse">
            <% if user_signed_in? %>
            <ul class="nav pull-right">
              <li><%= link_to "Edit account", edit_user_registration_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, {method: :delete, class: "btn btn-primary nav-custom-btn"} %></li>
            </ul>
            <p class="navbar-text pull-right" style="margin-right: 5px">
              Logged in as <strong><%= current_user.username %></strong> 
            </p>
            <% else %>
            <ul class="nav pull-right">
              <li><%= link_to "Create Account", new_user_registration_path(recommender: params[:recommender]) %></li>
              <li><%= link_to "Sign In", new_user_session_path, class: "btn btn-primary nav-custom-btn" %></li>
            </ul>
            <% end %>
            <ul class="nav">
              <li class="<%= 'active' if params[:action] == 'index' %>"><%= link_to("Home", home_index_path) %></li>
              <% if user_signed_in? %>
              <li class="<%= 'active' if params[:action] == 'play' %>"><%= link_to("My Gamble", gambgame_play_path) %></li>
              <% req_num = current_user.pending_requests.count %>
              <li class="<%= 'active' if params[:action] == 'pending_requests' %>"><%= link_to("My Gambtree#{req_num > 0 ? " (#{req_num})" : ''}", gambtree_pending_requests_path) %></li>
              <% end %>
              <li class="<%= 'active' if params[:action] == 'tutorial' %>"><%= link_to("Tutorial", home_tutorial_path) %></li>
              <li class="<%= 'active' if params[:action] == 'about' %>"><%= link_to("About", home_about_path) %></li>
              <li class="<%= 'active' if params[:action] == 'contact' %>"><%= link_to("Contact Us", home_new_message_path) %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
  	
    
    
    <div class="container-fluid">
      <div class="row-fluid">
        <% unless @show_tutorial %>
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <% if user_signed_in? %>
              <li>
                <%= image_tag "gambcoin_icon.png", size: "24x24", title: "Gambcoins", alt: "Gambcoins", class: "player_info" %>
                Your Gambcoins: <%= current_user.coins %></li>
              <li>
                <%= image_tag "gambseed_icon.png", size: "24x24", title: "Gambseeds", alt: "Gambseeds", class: "player_info" %>
                Your Gambseeds: <%= current_user.seeds %></li>
              <li>
                <%= image_tag "gambfruit_icon.png", size: "24x24", title: "Your Gambfruits", alt: "Your Gambfruits", class: "player_info" %>
                Your Gambfruits: <%= current_user.participating_gambfruits.length %></li>
              <% end %>
              <li>
                <%= image_tag "prize_icon.png", size: "24x24", title: "Gambgame prize", alt: "Gambgame prize", class: "player_info" %>
                Gambgame prize: <%= Gambgame.current.prize %></li>
              <li>
                <%= image_tag "players_icon.png", size: "24x24", title: "Gambgame players", alt: "Gambgame players", class: "player_info" %>
                Gambgame players: <%= Gambgame.current.current_players_number %></li>
              <% if user_signed_in? && current_user.gamble.nil? %>
              <li><br /><%= link_to "Gamble!", gambgame_play_path, class: "btn btn-primary btn-default btn-large sidebar-custom-btn" %></li>
              </li>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <% end %>
        <div class="<%= @show_tutorial ? 'span12' : 'span9' %>">
          <%= bootstrap_flash %>
          <% flash.each do |name, msg| %>
             <%= content_tag :div, msg, :id => "flash_#{name}" %>
          <% end %>
          <%= yield %>
        </div>
      </div><!--/row-->

<!--
      <footer>
        <p>&copy; Gambtree 2014</p>
      </footer>
-->

    </div> <!-- /container -->

</body>
</html>